---
title: "Proposal for a course in numerical methods for economists"
author: "William McCausland"
date: "04/03/2021"
output: pdf_document
---

# Required Texts

Main text

- Judd (1998), "Numerical Methods in Economics"

Free (i.e. willingly provided at no cost by the authors) supplementary texts

- Devroye (1986), "Non-Uniform Random Number Generation"
- Train (2009), "Discrete Choice Methods with Simulation", 2nd edition

Articles

- Geweke and Durham (2019), "Sequentially adaptive Bayesian learning algorithms for inference and optimization"

Various Wikipedia pages and instructor's notes

# Plan

## Introduction

Topics:

1. Mathematics and notation
    a. derivatives, gradient, Hessian and Jacobian
    a. Jordan decomposition
1. Computational complexity
    a. P, NP, NP complete, how a seemingly simpler problem (integer programming) is in fact radically more difficult than linear programming, in general.
    a. polynomial evaluation using Horner's method
    a. matrix-matrix multiplication using the Strassen algorithm ($O(n^{\log_2 7})$ rather than $O(n^3)$).
1. Error analysis
    a. machine precision, machine infinity
    a. truncating infinite sums
    a. error propagation and minimizing its extent
1. Serial and parallel processing
    a. embarassingly parallel problems
    a. problems that are efficiently solved using SIMD (Single Instruction, Multiple Data) architectures.

References:

1. Judd: 1, 2
1. Wikipedia articles on "P and NP", NP complete.
1. Instructor's notes on SIMD, embarassingly parallel problems.
1. Wikipedia page on Strassen algorithm for matrix multiplication

## Linear equations and iterative methods

1. LU, QR and Cholesky decompositions
    a. How and why to avoid computing the inverse of a matrix.
    a. Numerical issues (ill-conditioned problems)
1. Iterative methods for solving systems of linear equations and their convergence.
1. Applications :
    a. computing invariant distributions of discrete-state Markov chains.
    a. drawing multivariate normal random variates
    a. rotation of loading matrices in factor models

References

1. Judd: 3.1, 3.2, 3.5, 3.6, 3.8, 3.11
1. Instructor's notes on drawing multivariate normal variates.
1. Instructor's notes on identification and rotations in factor models.

## Random number generation

1. Pseudo-random numbers and the Mersenne Twister
1. Drawing non-uniform random variates
    a. inverse cdf method (Weibull example)
    a. accept-reject method (gamma example)
1. Quasi-random numbers
1. Importance sampling
1. Metropolis Hastings algorithm
1. Gibbs sampling
1. Applications : computing moments associated with target distributions
    a. simple posterior simulation
    a. simulating the value of a simple mixed-logit likelihood function

References

1. Judd: 8.1, 8.2, 8.3
1. Wikipedia page on Mersenne Twister (uniform random variates)
1. Wikipedia page on Ziggurat algorithm (Gaussian random variates)
1. Devroye II.2 and II.3 on the inverse cdf method and the accept-reject method
1. Instructor's notes on Metropolis-Hastings algorithm.
1. Instructor's notes on randomization of quasi-random numbers for importance sampling.
1. Instructor's notes on Bayesian inference.
1. Instructor's notes on mixed-logit models.

## An application: simulated maximum likelihood in discrete choice models

1. Introduction to discrete choice models
1. Simulated maximum likelihood for inference in discrete choice models

References

1. Train, Chapters 1, 2, 6, 10

## Static optimization

1. One-dimensional problems and bracketing.
1. Multivariate problems:
    a. comparison methods
    a. Newton's method and refinements
    a. Linear programming
    a. Non-linear optimization with constraints
1. Applications: solution of principal-agent problems, computing Nash equilibria of discrete-action games.
1. Additional applications: low-dimensional likelihood maximization (GARCH or proportional hazard model?)

References

1. Judd: 4.1, 4.2, 4.3, 4.4, 4.6, 4.7, 4.8, 4.9
1. Instructor's notes on maximum likelihood

## Solving non-linear equations

1. One-dimensional problems, bisection, Newton's method, stopping rules, convergence.
1. Multidimensional problems, Gauss-Jacobi and Gauss-Seidel, fixed point iteration, Newton's method, Broydon's method.
1. Application: computing duopoly equilibrium

References

1. Judd: 5.1, 5.2, 5.3, 5.4, 5.5

## Approximation methods

1. Local approximation, Taylor series, rational approximations
1. Orthogonal polynomials and least squares approximation
1. Uniform approximation
1. Interpolation
1. Piecewise polynomial interpolation, splines
1. Application: (to be determined, nothing satisfactory in Judd until later chapters)

References

1. Judd: 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.8, 6.9

## Numerical integration

1. Newton-Cotes
1. Unidimensional and Multidimensional Quadrature
1. Application: a portfolio problem

References

1. Judd: 7.1, 7.2, 7.3, 7.5, 7.6, 8.2

## Dynamic programming

1. Discrete-time Dynamic Programming Problems
1. Continuous-time Dynamic Programming Problems
1. Value function and policy function iteration
1. Application: stochastic accumulation problem

References

1. Judd: 12.1, 12.2, 12.3, 12.4, 12.5, 12.6

## Simulated annealing and Sequential Monte Carlo

1. Sequential Monte Carlo (SMC) theory
1. Simulated annealing seen as a special case of SMC
1. Application: maximum likelihood for a GARCH model with an otherwise intractable likelihood (in Durham and Geweke paper).
1. Application: Bayesian inference for the same GARCH model.

References

1. Durham and Geweke (2019)
