---
title: "Unused notes on P, NP"
author: "William McCausland"
date: "13/01/2022"
output: html_document
---

## Complexité et l'importance d'algorithmes d'ordre polynomial

* Soit $n$ le nombre de scalaires dans l'intrant du problème.
* L'ordre de complexité d'un problème est l'ordre de complexité du meilleur algorithme qui résoud le problème.
* Un algorithme est d'ordre polynomial si le nombre d'opérations est $O(g(n))$, pour une polynôme $g(n)$.
* Une distinction importante entre les problèmes "faisables" (pour lesquels il y a un algorithme polynomial connue pour le résoudre) et les problèmes "infaisables".
* Fonctions à sens unique et la cryptographie.
* Si un algorithme est polynomial, il est habituellement facile à prouver qu'il l'est.
    * Les polynômes sont stables pour l'addition, la multiplication et la composition :
    si $p(n)$ et $q(n)$ sont polynomiales, $p(n) + q(n)$, $p(n)q(n)$ et $p(q(n))$ le sont aussi.
    * (boucles, invocation des fonctions, etc.)

## P, NP, NP-complet, NP-difficile

- Une réduction : problème $A$ n'est pas plus difficile que $B$ ($A \leq_P B$) si $A$ peut être réduit à $B$---résolu par un algorithme pour résoudre $B$ plus un nombre d'opérations supplémentaires d'ordre polynomial.
- Classes de problèmes :
    * P : problèmes de décision (oui/no) résoluble en temps polynôme.
    * NP : problèmes de décision (oui/non) ou une réponse affirmative peut être prouvé correcte en temps polynôme.
    * NP-complet : les problèmes en NP les plus difficiles (une classe d'équivalence avec plusieurs exemples connus)
    * NP-difficile : les problèmes qui sont au moins aussi difficile que les problèmes dans NP-complet.
- P=NP? est une question non-résolue : il n'y a pas d'algorithmes polynômes connus pour résoudre les problèmes en NP.

## Quelques problèmes

\definecolor{amber}{rgb}{1.0,0.75,0.0}
(\textcolor{green}{polynomial}, \textcolor{amber}{NP-complet}, \textcolor{red}{NP-difficile})

### Problème du voyageur de commerce (Travelling Salesman)

\definecolor{amber}{rgb}{1.0,0.75,0.0}
* \textcolor{red}{Trouvez le trajet le plus court qui relie un ensemble de villes.}
* \textcolor{amber}{Y a-t-il un trajet plus court que $L$ qui relie les villes?}

### Optimisation linéaire en nombres entiers (Integer programming)

\definecolor{amber}{rgb}{1.0,0.75,0.0}
* \textcolor{red}{Trouvez la solution optimale ou montrez qu'il n'y a pas de solution.}
* \textcolor{amber}{(Cas spécial de variables binaires) Y a-t-il une solution faisable?}

### Optimisation linéaire (Linear programming)

* \textcolor{green}{Trouvez la solution optimale ou montrez qu'il n'y a pas de solution.}
